
rm(list=ls(all=T))

library(vars)
library(tsDyn)
#options(scipen=8, digits=8)  #This options command prints output in standard notation

setwd("C:/Users/sabaric/Documents/Revolution/CPI PROJECT")  # set working directory 

cpidat <- read.csv("C:/Users/sabaric/Documents/Revolution/CPI PROJECT/SABADAT.csv", header = TRUE)
cpidat<-ts(cpidat,start=c(1974,1),freq=12)
lvar <- VAR(cpidat[ ,c("ROP","RAP","RCN")], p = 2, type = "both")

x <- lvar 

n.ahead = 10 ; ortho = TRUE ;cumulative = FALSE; boot = FALSE; ci = NULL; runs = NULL; seed = NULL
impulse = "ROP"; response = c("RAP", "RCN")

  if (!(class(x) == "varest")) {
    stop("\nPlease provide an object of class 'varest', generated by 'VAR()'.\n")
  }
  y.names <- colnames(x$y)
  if (is.null(impulse)) {
    impulse <- y.names
  }   else {
    impulse <- as.vector(as.character(impulse))
    if (any(!(impulse %in% y.names))) {
      stop("\nPlease provide variables names in impulse\nthat are in the set of endogenous variables.\n")
    }
    impulse <- subset(y.names, subset = y.names %in% impulse)
  }
  if (is.null(response)) {
    response <- y.names
  }  else {
    response <- as.vector(as.character(response))
    if (any(!(response %in% y.names))) {
      stop("\nPlease provide variables names in response\nthat are in the set of endogenous variables.\n")
    }
    response <- subset(y.names, subset = y.names %in% response)
  }
nstep <- 4

nstep <- abs(as.integer(nstep))
K <- x$K
p <- x$p
A <- as.array(Acoef(x))
if (nstep >= p) {
  As <- array(0, dim = c(K, K, nstep + 1))
  for (i in (p + 1):(nstep + 1)) {
    As[, , i] <- matrix(0, nrow = K, ncol = K)
  }
}else {
  As <- array(0, dim = c(K, K, p))
}
for (i in 1:p) {
  As[, , i] <- A[[i]]
}
Phi <- array(0, dim = c(K, K, nstep + 1))
Phi[, , 1] <- diag(K)
Phi[, , 2] <- Phi[, , 1] %*% As[, , 1]
if (nstep > 1) {
  for (i in 3:(nstep + 1)) {
    tmp1 <- Phi[, , 1] %*% As[, , i - 1]
    tmp2 <- matrix(0, nrow = K, ncol = K)
    idx <- (i - 2):1
    for (j in 1:(i - 2)) {
      tmp2 <- tmp2 + Phi[, , j + 1] %*% As[, , idx[j]]
    }
    Phi[, , i] <- tmp1 + tmp2
  }
}
Phi
